name: icloud_storage_sync
description: Easily sync and secure your app's data with the iCloud Sync Flutter plugin for seamless iCloud integration.
version: 0.0.3
homepage: https://github.com/DevCodeSpace/icloud_storage_sync
issue_tracker: https://github.com/DevCodeSpace/icloud_storage_sync/issues
documentation: https://pub.dev/documentation/icloud_storage_sync/latest/

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: 'The iCloud storage sync Flutter plugin integrates iCloud, enabling secure backup and sync of data across devices.'
    path: screenshots/screenshot1.jpg

# For information on the generic Dart part of this file, see the
following page: https://github.com/DevCodeSpace

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IcloudStorageSyncPlugin
      macos:
        pluginClass: IcloudStorageSyncPlugin

  